#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqDemo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="remote")]
	public partial class TableFillDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    #endregion
		
		public TableFillDataContext() : 
				base(global::LinqDemo.Properties.Settings.Default.remoteConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TableFillDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TableFillDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TableFillDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TableFillDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ty_FillTableList> ty_FillTableList
		{
			get
			{
				return this.GetTable<ty_FillTableList>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ty_FillTableList")]
	public partial class ty_FillTableList
	{
		
		private System.Nullable<int> _lIndex;
		
		private string _sVoucherKey;
		
		private string _sVoucherName;
		
		private System.Nullable<int> _lArchiveIndex;
		
		private string _sTableName;
		
		private string _sHadUseCode;
		
		private string _SealID;
		
		private string _WriteTime;
		
		private string _signInfo;
		
		private string _sTableGroupName;
		
		private string _UpdateTime;
		
		private System.Nullable<int> _iState;
		
		public ty_FillTableList()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lIndex", DbType="Int")]
		public System.Nullable<int> lIndex
		{
			get
			{
				return this._lIndex;
			}
			set
			{
				if ((this._lIndex != value))
				{
					this._lIndex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sVoucherKey", DbType="VarChar(64)")]
		public string sVoucherKey
		{
			get
			{
				return this._sVoucherKey;
			}
			set
			{
				if ((this._sVoucherKey != value))
				{
					this._sVoucherKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sVoucherName", DbType="VarChar(200)")]
		public string sVoucherName
		{
			get
			{
				return this._sVoucherName;
			}
			set
			{
				if ((this._sVoucherName != value))
				{
					this._sVoucherName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lArchiveIndex", DbType="Int")]
		public System.Nullable<int> lArchiveIndex
		{
			get
			{
				return this._lArchiveIndex;
			}
			set
			{
				if ((this._lArchiveIndex != value))
				{
					this._lArchiveIndex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sTableName", DbType="VarChar(40)")]
		public string sTableName
		{
			get
			{
				return this._sTableName;
			}
			set
			{
				if ((this._sTableName != value))
				{
					this._sTableName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sHadUseCode", DbType="VarChar(20)")]
		public string sHadUseCode
		{
			get
			{
				return this._sHadUseCode;
			}
			set
			{
				if ((this._sHadUseCode != value))
				{
					this._sHadUseCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SealID", DbType="VarChar(10)")]
		public string SealID
		{
			get
			{
				return this._SealID;
			}
			set
			{
				if ((this._SealID != value))
				{
					this._SealID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WriteTime", DbType="VarChar(19)")]
		public string WriteTime
		{
			get
			{
				return this._WriteTime;
			}
			set
			{
				if ((this._WriteTime != value))
				{
					this._WriteTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_signInfo", DbType="VarChar(256)")]
		public string signInfo
		{
			get
			{
				return this._signInfo;
			}
			set
			{
				if ((this._signInfo != value))
				{
					this._signInfo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sTableGroupName", DbType="VarChar(40)")]
		public string sTableGroupName
		{
			get
			{
				return this._sTableGroupName;
			}
			set
			{
				if ((this._sTableGroupName != value))
				{
					this._sTableGroupName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateTime", DbType="VarChar(19)")]
		public string UpdateTime
		{
			get
			{
				return this._UpdateTime;
			}
			set
			{
				if ((this._UpdateTime != value))
				{
					this._UpdateTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iState", DbType="Int")]
		public System.Nullable<int> iState
		{
			get
			{
				return this._iState;
			}
			set
			{
				if ((this._iState != value))
				{
					this._iState = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
